version: '3.8'

networks:
  barrio-network:
    name: barrio-network
    driver: bridge

services:
  rabbitmq1:
    image: rabbitmq:3.13-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: "SECRET_COOKIE_BARRIO_DIGITAL"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - barrio-network

  rabbitmq2:
    image: rabbitmq:3.13-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: "SECRET_COOKIE_BARRIO_DIGITAL"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
      - rabbitmq1
    networks:
      - barrio-network